media: images
content:
  - name: posts
    label: Posts
    type: collection
    path: vlog
    view:
      fields: [ published ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text